### ISSUE TITLE
Combo unknown monomer looks like sugar and linker only

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#146]
The combo unknown monomer puts two monomers into the molecule. 
![image](https://user-images.githubusercontent.com/3986896/33986648-212f2bc2-e0b6-11e7-934c-25b44a8f724e.png)

This is confusing as it looks like the * represents a single monomer and there is no base. it would be better if there was a single monomer and it had a different shape (e.g. pentagon) to indicate that * can mean anything.

**Comment by scilligence** [comment]
The problem is how to intercept the * in the HELM.  For example, for this HELM:

RNA1{R(A)P.R(U)P.*.R(T)P.R(G)}$$$$V2.0

Should the * be explained as a nucleotide(combo), or a isolated Ribose, or an extra Phophate.  Since in HELM 2.0 they are also valid:

RNA1{R(A)P.R(U)P.**R**.R(T)P.R(G)}$$$$V2.0

RNA1{R(A)P.R(U)P.**P**.R(T)P.R(G)}$$$$V2.0

**Comment by ClairePA** [comment]
* means anything which is why it should not be specified that it means a nucleotide(combo), or a isolated Ribose, or an extra Phosphate. There should be no implied interpretation.

**Comment by scilligence** [comment]
fixed in 2018-01-10 update

**Comment by ClairePA** [comment]
Confirmed fixed.
