### ISSUE TITLE
Can't define X as a connection point in webservices

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#186]
The following HELM string is valid 
`PEPTIDE1{A.X.G.C.T.C.F.D.W.C}|BLOB1{BEAD}$PEPTIDE1,BLOB1,A:?-?:?$$$V2.0`

However if I substitute X for A in the connection 
`PEPTIDE1{A.X.G.C.T.C.F.D.W.C}|BLOB1{BEAD}$PEPTIDE1,BLOB1,X:?-?:?$$$V2.0`

The webservices says the HELM is invalid. This is incorrect, the HELM string is fine. 

The webeditor can handle this string, and displays correctly.

**Comment by MarkusWeisser** [comment]
On http://webeditor.openhelm.org/hwe/examples/App.htm, 
`PEPTIDE1{A.X.G}$$$V2.0`
So, we still have the refresh issue.

**Comment by ClairePA** [comment]
I am confused. I thought both these pages used the same webservice components:
(http://54.83.135.171/WebService/FirstPage.html)[http://54.83.135.171/HELM2MonomerService/hwe/examples/App.htm

but `PEPTIDE1{A.X.G}$$$V2.0`
is valid according to the webeditor validation button (which I thought called the webservices)
but not valid according to the webservices page. Are they using different components? 

Help.

**Comment by MarkusWeisser** [comment]
Sorry, I always get confused with "X" as the notation for one single amino acid in peptides.
The toolkit currently has an issue on recognizing "X" during validation of the connection section. 

PEPTIDE1{A.*.G.C.T.C.F.D.W.C}|BLOB1{BEAD}$PEPTIDE1,BLOB1,*:?-?:?$$$V2.0 is valid and
PEPTIDE1{A.*.G.C.T.C.F.D.W.C}|BLOB1{BEAD}$PEPTIDE1,BLOB1,2:?-?:?$$$V2.0 as well.

Should work with X in the same way.

BTW: PEPTIDE1{A.X.G}$$$V2.0 is not valid because of a missing $-symbol.

**Comment by ClairePA** [comment]
Retested - fixed.
